# Generated by Django 2.2.4 on 2019-08-17 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190717_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_date',
            new_name='create_date3',
        ),
    ]
